{ pkgs }:
{
  mkWebAppAutoconfig =
    appId: userscripts:
    let
      scripts = builtins.toJSON (
        map (u: {
          inherit (u) name hosts;
          code = u.script;
        }) userscripts
      );
      frameScript = ''
        // [web-apps] userscript frame script (generated by nix)
        // ES5 only (see bootstrap note).
        try {
          var Cc = Components.classes;
          var Ci = Components.interfaces;
          var setP = function (k, v) {
            try {
              Cc["@mozilla.org/preferences-service;1"].getService(Ci.nsIPrefBranch).setCharPref(k, v);
            } catch (e) {}
          };
          var scripts = ${scripts};
          setP("webapps.frame", "registered");
          try {
            var os = Cc["@mozilla.org/observer-service;1"].getService(Ci.nsIObserverService);
            os.addObserver({
              observe: function (subject) {
                try {
                  var doc = subject;
                  if (!doc.location || !doc.location.host) return;
                  var win = doc.defaultView;
                  if (!win || win.top !== win) return;
                  for (var i = 0; i < scripts.length; i++) {
                    if (scripts[i].hosts.indexOf(doc.location.host) !== -1) {
                      try {
                        win.wrappedJSObject.eval(scripts[i].code);
                        setP("webapps.injected." + scripts[i].name, "ok");
                      } catch (e) {
                        setP("webapps.error." + scripts[i].name, String(e));
                      }
                      return;
                    }
                  }
                } catch (e) {
                  setP("webapps.error.observer", String(e));
                }
              }
            }, "document-element-inserted", false);
          } catch (eObs) {
            setP("webapps.error.observer", String(eObs));
          }
        } catch (e) {}
      '';
      frameScriptJson = builtins.toJSON frameScript;
    in
    pkgs.writeText "webapp-autoconfig-${appId}.js" ''
      // [web-apps] userscript bootstrap (generated by nix)
      // ES5 only: the autoconfig JS dialect may reject modern syntax.
      // Registers the (embedded) frame script with the message manager via a
      // data: URI. Every attempt is logged to the webapps.log pref.
      pref("webapps.probe.default", "1");
      try {
        var Cc = Components.classes;
        var Ci = Components.interfaces;
        var setP = function (k, v) {
          try {
            Cc["@mozilla.org/preferences-service;1"].getService(Ci.nsIPrefBranch).setCharPref(k, v);
          } catch (e) {}
        };
        var log = function (msg) {
          try {
            var branch = Cc["@mozilla.org/preferences-service;1"].getService(Ci.nsIPrefBranch);
            var prev = "";
            try { prev = branch.getCharPref("webapps.log"); } catch (ePrev) {}
            var next = prev + (prev ? " | " : "") + msg;
            if (next.length > 4000) next = next.substr(next.length - 4000);
            branch.setCharPref("webapps.log", next);
            branch.setCharPref("webapps.step", msg);
          } catch (eLog) {}
        };

        var frameScript = ${frameScriptJson};
        var dataUrl = "data:;charset=utf-8," + encodeURIComponent(frameScript);
        var registered = false;

        // First log entry: which Firefox is running — makes future
        // version-dependent breakage ("worked on 153, broke on X") obvious.
        try {
          var appInfo = Cc["@mozilla.org/xre/app-info;1"].getService(Ci.nsIXULAppInfo);
          log("ff " + appInfo.version + " (" + appInfo.appBuildID + ")");
        } catch (eVer) {
          log("ff version lookup failed: " + eVer);
        }

        var msgIfaces = [];
        try {
          for (var ciKey in Ci) { if (/essage/.test(ciKey)) msgIfaces.push(ciKey); }
        } catch (eCi) {}
        log("message interfaces: " + (msgIfaces.length ? msgIfaces.join(",") : "(none/enumeration failed)"));

        // Find a message manager with loadFrameScript, trying modern and
        // legacy spellings (FF 153 removed Ci.nsIMessageListenerManager).
        var findMm = function () {
          var mm = null;
          try {
            if (typeof ChromeUtils !== "undefined" && ChromeUtils.importESModule) {
              var svc = ChromeUtils.importESModule("resource://gre/modules/Services.sys.mjs").Services;
              if (svc && svc.mm && typeof svc.mm.loadFrameScript === "function") {
                mm = svc.mm;
                log("mm found: Services.mm");
              } else {
                log("Services.mm: " + (svc ? typeof svc.mm : "no Services"));
              }
            } else {
              log("ChromeUtils: " + typeof ChromeUtils);
            }
          } catch (eA) { log("Services.mm lookup failed: " + eA); }
          if (!mm) {
            var comps = ["@mozilla.org/globalmessagemanager;1", "@mozilla.org/parentprocessmessagemanager;1", "@mozilla.org/childprocessmessagemanager;1"];
            var ifaces = ["nsIMessageListenerManager", "nsIGlobalMessageManager", "nsIMessageBroadcaster", "nsISyncMessageSender", "nsIMessageSender"];
            for (var c = 0; c < comps.length && !mm; c++) {
              var comp = null;
              try { comp = Cc[comps[c]]; } catch (eComp) {}
              if (!comp) { log(comps[c] + ": absent"); continue; }
              for (var n = 0; n < ifaces.length && !mm; n++) {
                try {
                  var iface = Ci[ifaces[n]];
                  if (!iface) continue;
                  var cand = comp.getService(iface);
                  if (cand && typeof cand.loadFrameScript === "function") {
                    mm = cand;
                    log("mm found: " + comps[c] + " as " + ifaces[n]);
                  }
                } catch (eQ) {}
              }
            }
          }
          if (!mm) {
            try {
              var raw = Cc["@mozilla.org/globalmessagemanager;1"].getService();
              if (raw && typeof raw.loadFrameScript === "function") {
                mm = raw;
                log("mm found: globalmessagemanager default interface");
              }
            } catch (eRaw) { log("default-interface lookup failed: " + eRaw); }
          }
          return mm;
        };

        var mm = findMm();
        if (mm) {
          try {
            mm.loadFrameScript(dataUrl, true);
            registered = true;
            log("registered via data: URI");
          } catch (eData) {
            log("data: URI loadFrameScript failed: " + eData);
          }
        } else {
          log("no message manager with loadFrameScript found");
        }

        setP("webapps.bootstrap", registered ? "frame script registered" : "no strategy worked - see webapps.log");
        if (!registered) {
          try { Components.utils.reportError("[web-apps] bootstrap: all frame-script registration strategies failed"); } catch (eR) {}
        }
      } catch (e) {
        setP("webapps.bootstrap", "error: " + e);
        try { Components.utils.reportError("[web-apps] bootstrap error: " + e); } catch (e2) {}
      }
    '';
}
