{
  lib,
  pkgs,
  config,
  ...
}:
let
  # Stable 32-bit numeric ID derived from the profile name to avoid manually tracking profile IDs
  mkProfileId =
    name:
    let
      hex = builtins.hashString "sha1" name;
      shortHex = builtins.substring 0 8 hex;
      id = lib.fromHexString shortHex; # Convert hex to decimal
    in
    id;

  # Deterministic moz-extension:// UUID for an addon ID. Extensions map
  # their host UUID in the `extensions.webextensions.uuids' pref; pinning it
  # keeps `storage/default/moz-extension+++<uuid>/' stable across profile
  # regeneration so persisted extension data survives reboots.
  mkUuid =
    addonId:
    let
      hex = builtins.hashString "sha256" addonId;
    in
    lib.concatStringsSep "-" [
      (builtins.substring 0 8 hex)
      (builtins.substring 8 4 hex)
      (builtins.substring 12 4 hex)
      (builtins.substring 16 4 hex)
      (builtins.substring 20 12 hex)
    ];

  webappPolicies = import ./policies.nix;
  prefs = import ../prefs;
  webAppSingleMinimal = (import ../user-chrome).webAppSingleMinimal;

  # Derive a bare origin (scheme + host, no path) from an app URL — the
  # Permissions.Notifications policy schema accepts bare origins only.
  originOfUrl =
    url:
    let
      noScheme = lib.removePrefix "https://" url;
    in
    "https://" + (builtins.head (builtins.split "/" noScheme));

  # New Tab Override is force-installed in every webapp (via ExtensionSettings)
  # and configured through managed storage (3rdparty policy).
  newTabOverrideId = "newtaboverride@agenedia.com";
  newTabOverrideSlug = "new-tab-override";

  # UUID pinning pref: keeps moz-extension UUIDs stable across profile
  # regeneration so the persisted extension data under
  # `storage/default/moz-extension+++<uuid>/' survives reboots.
  webAppExtensionPrefs =
    extraAddons:
    let
      ids = (map (a: a.id) extraAddons) ++ [ newTabOverrideId ];
      uuids = builtins.listToAttrs (
        map (id: {
          name = id;
          value = mkUuid id;
        }) ids
      );
    in
    {
      "extensions.webextensions.uuids" = builtins.toJSON uuids;
    };

  # ExtensionSettings enterprise policy following the NixOS wiki pattern
  mkWebAppExtensionSettings =
    extraAddons:
    lib.listToAttrs (
      [
        {
          name = "*";
          value = {
            installation_mode = "blocked";
          };
        }
      ]
      ++
        map
          (a: {
            name = a.id;
            value = {
              installation_mode = "force_installed";
              install_url = "https://addons.mozilla.org/firefox/downloads/latest/${a.slug}/latest.xpi";
              updates_disabled = true;
            };
          })
          (
            extraAddons
            ++ [
              {
                id = newTabOverrideId;
                slug = newTabOverrideSlug;
              }
            ]
          )
    );

  webAppIcons = pkgs.stdenv.mkDerivation {
    name = "webapp-icons";
    src = ./icons;
    installPhase = ''
      mkdir -p $out/share/icons/webapps
      cp -r * $out/share/icons/webapps/
    '';
  };

  # Autoconfig payload for userscript injection: the nixpkgs wrapper appends
  # `extraPrefsFiles' contents into `lib/firefox/mozilla.cfg', which Firefox
  # executes with system privileges at startup (shipped bootstrap:
  # defaults/pref/autoconfig.js, obscure_value 0).
  mkWebAppAutoconfig =
    appId: userscripts:
    let
      scripts = builtins.toJSON (
        map (u: {
          inherit (u) name hosts;
          code = u.script;
        }) userscripts
      );
      frameScript = ''
        // [web-apps] userscript frame script (generated by nix)
        // ES5 only (see bootstrap note).
        try {
          var Cc = Components.classes;
          var Ci = Components.interfaces;
          var setP = function (k, v) {
            try {
              Cc["@mozilla.org/preferences-service;1"].getService(Ci.nsIPrefBranch).setCharPref(k, v);
            } catch (e) {}
          };
          var scripts = ${scripts};
          setP("webapps.frame", "registered");
          try {
            var os = Cc["@mozilla.org/observer-service;1"].getService(Ci.nsIObserverService);
            os.addObserver({
              observe: function (subject) {
                try {
                  var doc = subject;
                  if (!doc.location || !doc.location.host) return;
                  var win = doc.defaultView;
                  if (!win || win.top !== win) return;
                  for (var i = 0; i < scripts.length; i++) {
                    if (scripts[i].hosts.indexOf(doc.location.host) !== -1) {
                      try {
                        win.wrappedJSObject.eval(scripts[i].code);
                        setP("webapps.injected." + scripts[i].name, "ok");
                      } catch (e) {
                        setP("webapps.error." + scripts[i].name, String(e));
                      }
                      return;
                    }
                  }
                } catch (e) {
                  setP("webapps.error.observer", String(e));
                }
              }
            }, "document-element-inserted", false);
          } catch (eObs) {
            setP("webapps.error.observer", String(eObs));
          }
        } catch (e) {}
      '';
      frameScriptJson = builtins.toJSON frameScript;
    in
    pkgs.writeText "webapp-autoconfig-${appId}.js" ''
      // [web-apps] userscript bootstrap (generated by nix)
      // ES5 only: the autoconfig JS dialect may reject modern syntax.
      // Registers the (embedded) frame script with the message manager via a
      // data: URI. Every attempt is logged to the webapps.log pref.
      pref("webapps.probe.default", "1");
      try {
        var Cc = Components.classes;
        var Ci = Components.interfaces;
        var setP = function (k, v) {
          try {
            Cc["@mozilla.org/preferences-service;1"].getService(Ci.nsIPrefBranch).setCharPref(k, v);
          } catch (e) {}
        };
        var log = function (msg) {
          try {
            var branch = Cc["@mozilla.org/preferences-service;1"].getService(Ci.nsIPrefBranch);
            var prev = "";
            try { prev = branch.getCharPref("webapps.log"); } catch (ePrev) {}
            var next = prev + (prev ? " | " : "") + msg;
            if (next.length > 4000) next = next.substr(next.length - 4000);
            branch.setCharPref("webapps.log", next);
            branch.setCharPref("webapps.step", msg);
          } catch (eLog) {}
        };

        var frameScript = ${frameScriptJson};
        var dataUrl = "data:;charset=utf-8," + encodeURIComponent(frameScript);
        var registered = false;

        // First log entry: which Firefox is running — makes future
        // version-dependent breakage ("worked on 153, broke on X") obvious.
        try {
          var appInfo = Cc["@mozilla.org/xre/app-info;1"].getService(Ci.nsIXULAppInfo);
          log("ff " + appInfo.version + " (" + appInfo.appBuildID + ")");
        } catch (eVer) {
          log("ff version lookup failed: " + eVer);
        }

        var msgIfaces = [];
        try {
          for (var ciKey in Ci) { if (/essage/.test(ciKey)) msgIfaces.push(ciKey); }
        } catch (eCi) {}
        log("message interfaces: " + (msgIfaces.length ? msgIfaces.join(",") : "(none/enumeration failed)"));

        // Find a message manager with loadFrameScript, trying modern and
        // legacy spellings (FF 153 removed Ci.nsIMessageListenerManager).
        var findMm = function () {
          var mm = null;
          try {
            if (typeof ChromeUtils !== "undefined" && ChromeUtils.importESModule) {
              var svc = ChromeUtils.importESModule("resource://gre/modules/Services.sys.mjs").Services;
              if (svc && svc.mm && typeof svc.mm.loadFrameScript === "function") {
                mm = svc.mm;
                log("mm found: Services.mm");
              } else {
                log("Services.mm: " + (svc ? typeof svc.mm : "no Services"));
              }
            } else {
              log("ChromeUtils: " + typeof ChromeUtils);
            }
          } catch (eA) { log("Services.mm lookup failed: " + eA); }
          if (!mm) {
            var comps = ["@mozilla.org/globalmessagemanager;1", "@mozilla.org/parentprocessmessagemanager;1", "@mozilla.org/childprocessmessagemanager;1"];
            var ifaces = ["nsIMessageListenerManager", "nsIGlobalMessageManager", "nsIMessageBroadcaster", "nsISyncMessageSender", "nsIMessageSender"];
            for (var c = 0; c < comps.length && !mm; c++) {
              var comp = null;
              try { comp = Cc[comps[c]]; } catch (eComp) {}
              if (!comp) { log(comps[c] + ": absent"); continue; }
              for (var n = 0; n < ifaces.length && !mm; n++) {
                try {
                  var iface = Ci[ifaces[n]];
                  if (!iface) continue;
                  var cand = comp.getService(iface);
                  if (cand && typeof cand.loadFrameScript === "function") {
                    mm = cand;
                    log("mm found: " + comps[c] + " as " + ifaces[n]);
                  }
                } catch (eQ) {}
              }
            }
          }
          if (!mm) {
            try {
              var raw = Cc["@mozilla.org/globalmessagemanager;1"].getService();
              if (raw && typeof raw.loadFrameScript === "function") {
                mm = raw;
                log("mm found: globalmessagemanager default interface");
              }
            } catch (eRaw) { log("default-interface lookup failed: " + eRaw); }
          }
          return mm;
        };

        var mm = findMm();
        if (mm) {
          try {
            mm.loadFrameScript(dataUrl, true);
            registered = true;
            log("registered via data: URI");
          } catch (eData) {
            log("data: URI loadFrameScript failed: " + eData);
          }
        } else {
          log("no message manager with loadFrameScript found");
        }

        setP("webapps.bootstrap", registered ? "frame script registered" : "no strategy worked - see webapps.log");
        if (!registered) {
          try { Components.utils.reportError("[web-apps] bootstrap: all frame-script registration strategies failed"); } catch (eR) {}
        }
      } catch (e) {
        setP("webapps.bootstrap", "error: " + e);
        try { Components.utils.reportError("[web-apps] bootstrap error: " + e); } catch (e2) {}
      }
    '';

  # Per-webapp Firefox binary. Enterprise policies are per-binary
  # (distribution/policies.json), so each webapp launches its own wrapped
  # Firefox carrying the shared webapp baseline merged with the app's own
  # `policies' overrides, the generated ExtensionSettings, and the New Tab
  # Override managed-storage config (3rdparty policy -> browser.storage.managed,
  # which the addon treats as authoritative). Identical policy sets share one
  # wrapper derivation.
  mkWebAppPackage =
    app: extraAddons:
    let
      appPolicies = app.policies or { };
      userscripts = app.userscripts or [ ];
      autoconfigJs = lib.optionals (userscripts != [ ]) [
        (mkWebAppAutoconfig app.id userscripts)
      ];
    in
    pkgs.firefox.override (old: {
      extraPolicies =
        (old.extraPolicies or { })
        // webappPolicies.webAppPolicies
        // appPolicies
        // {
          ExtensionSettings =
            (mkWebAppExtensionSettings extraAddons) // (appPolicies.ExtensionSettings or { });
          "3rdparty" = {
            Extensions = ((appPolicies."3rdparty" or { }).Extensions or { }) // {
              ${newTabOverrideId} = {
                type = "custom_url";
                url = app.url;
              };
            };
          };
        };
      extraPrefsFiles = (old.extraPrefsFiles or [ ]) ++ autoconfigJs;
    });

  mkWebAppEntry =
    app:
    let
      pkg = app.package or pkgs.firefox;
    in
    {
      inherit (app) name;
      type = "Application";
      exec = "${pkg}/bin/firefox -no-remote --profile \"${config.xdg.configHome}/mozilla/firefox/${app.id}\" --class \"${app.id}\" --name \"${app.name}\" --new-window \"${app.url}\"";
      icon = "${webAppIcons}/share/icons/webapps/${app.icon}";
      categories = [ "X-Internet" ];
      settings = {
        Keywords = "WebApp";
        StartupWMClass = app.id;
      };
    };

  # Factory for a web app module: one attrset generates the per-app enable
  # option, the wrapped per-webapp Firefox binary, the profile (settings +
  # userChrome), and the XDG desktop entry. Apps simply call this with their
  # `id'/'name'/'url' and optional addons/settings/userChrome/policies.
  mkWebAppModule =
    {
      id,
      name,
      url,
      icon ? "${id}.svg",
      addons ? [ ],
      settings ? { },
      userChrome ? null,
      policies ? { },
      grantNotifications ? false,
      savePasswords ? false,
      # Persist the entire profile directory (full state retention: session
      # restore, prefs, extensions registry, everything survives reboots).
      persistWholeProfile ? false,
      userscripts ? [ ],
    }:
    let
      effectivePolicies =
        policies
        // lib.optionalAttrs grantNotifications {
          Permissions.Notifications.Allow = [ (originOfUrl url) ];
        };

      effectiveSettings = {
        "browser.startup.homepage" = url;
      }
      // lib.optionalAttrs savePasswords {
        "signon.rememberSignons" = true;
      }
      // settings;
    in
    {
      options.myhome.web-apps.${id} = {
        enable = lib.mkEnableOption "${name} web app";
        persistWholeProfile = lib.mkEnableOption "persist the entire profile directory for ${name} (full state retention)";
      };

      config = lib.mkIf config.myhome.web-apps.${id}.enable {
        myhome.web-apps.${id}.persistWholeProfile = lib.mkDefault persistWholeProfile;

        programs.firefox.profiles.${id} = {
          id = mkProfileId id;
          settings = prefs.webApp // effectiveSettings // webAppExtensionPrefs addons;
          userChrome = if userChrome == null then webAppSingleMinimal else userChrome;
        };

        xdg.desktopEntries.${id} = mkWebAppEntry {
          inherit
            id
            name
            url
            icon
            ;
          package = mkWebAppPackage {
            inherit
              id
              url
              userscripts
              ;
            policies = effectivePolicies;
          } addons;
        };

        assertions = [
          {
            assertion = builtins.pathExists "${./icons}/${icon}";
            message = "[web-apps] ${id}: missing icon file icons/${icon}";
          }
        ];
      };
    };
in
{
  inherit
    mkWebAppEntry
    mkProfileId
    mkUuid
    mkWebAppPackage
    mkWebAppModule
    mkWebAppAutoconfig
    webAppExtensionPrefs
    ;
}
